package edu.rit.codelanx.cmd;

@Deprecated
public enum UtilsFlag {
    MISSINGPARAMS,
    DUPLICATEVISITOR,
    ALREADYVISITING,
    INVALIDVISITORID,
    TOOMANYBOOKS,
    OUTSTANDINGFINE,
    INVALIDSORTORDER,
    INVALIDDAYS,
    INVALIDHOURS,
    CORRECT,
    ERROR
}
