package edu.rit.codelanx.cmd;

public enum UtilsFlag {
    MISSINGPARAMS,
    DUPLICATEVISITOR,
    ALREADYVISITING,
    INVALIDVISITORID,
    TOOMANYBOOKS,
    OUTSTANDINGFINE,
    INVALIDSORTORDER,
    INVALIDDAYS,
    INVALIDHOURS,
    CORRECT
}
